#!/usr/bin/env python

from similaritymeasures import Similarity
import pandas as pd
import random
nofrow=10-1
nofcol=10
df = pd.read_csv('dane.csv')
row1=random.randint(0,nofrow)
row2=random.randint(0,nofrow)
while row1==row2:
    row2=random.randint(0,nofrow)
#print(row1)
#print(row2)
ncol=random.randint(1,nofcol)
#ncol=10
#print(ncol)
zakres=range(0,nofcol)
#if ncol==nofcol:
 #   col=range(0,nofcol)
#else:
col=random.sample(zakres,ncol)
#print(col)
x=df.iloc[[row1],col]
y=df.iloc[[row2],col]
print(x)
print(y)
#print (df.iat[x,5])
#measures = Similarity()
#print (measures.euclidean_distance(x,y))
#print (measures.jaccard_similarity(x,y))
